name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup OpenGL
        uses: openrndr/setup-opengl@v1.0.0

      - name: Build
        run: ./gradlew build

      - name: Smoke Test
        run: ./gradlew smokeTest
